### ISSUE TITLE
Тестовый репорт

### ISSUE THREAD

**Issue by svyatoslavratov** [skyrim-multiplayer/issue-tracker#1]
## Описание

Как можно более ясно и точно опишите, в чём заключается баг.

## Воспроизведение

Опишите инструкцию по вызову бага, то есть последовательность действий, которая, как вы считаете, вызывает проблему.
Разработчик должен понимать, как вызвать баг у себя.

## Вероятность воспроизведения

С какой вероятностью исполнение инструкции выше вызывает баг? Например, всегда (100%) или редко (5-10%).
Постарайтесь дать как можно более точную оценку.

## Ожидаемый результат

К какому результату должна приводить инструкция по воспроизведению после исправления бага?

## Среда исполнения

Версия Windows.
Steam-версия Skyrim SE или нет.

## Видео/скриншоты

Если баг воспроизводится не всегда, либо для этого требуется более 1-2 игроков, приложите видео.

**Comment by Pospelove** [comment]
Не получает воспроизвести? Как мне вызвать этот баг? Инструкция не работает
