### ISSUE TITLE
Проблемы с золотом

### ISSUE THREAD

**Issue by LambertSkymp** [skyrim-multiplayer/issue-tracker#10]
## Описание

При выходе и потом входе, пропадает всё золото, так-же не имея золото или имея оно будет автоматически пополнятся спустя время. 

## Воспроизведение

При входе всегда будешь начинать без золота, и оно постепенно будет расти

## Локация, FormID

Везде

## Вероятность воспроизведения

100%

## Ожидаемый результат

Игрок при входе должен иметь столько же золото сколько было когда он вышел, золото не должно добавляться автоматически спустя время, это его обесценивает.

## Среда исполнения

Windows 10
Steam-версия Skyrim SE

## Видео/скриншоты
![ScreenShot14](https://user-images.githubusercontent.com/74125507/98465612-c06ab700-21d2-11eb-85ce-3126656b07cb.png)
![ScreenShot15](https://user-images.githubusercontent.com/74125507/98465630-e728ed80-21d2-11eb-8ea2-ec29ee9474c1.png)
Перезаход
![ScreenShot16](https://user-images.githubusercontent.com/74125507/98465652-14759b80-21d3-11eb-9b37-b57a83eabf75.png)

**Comment by Pospelove** [comment]
Не удаётся воспроизвести, просто находясь в игре. Может быть, нужно подбирать кошельки или золото из сундуков?

**Comment by LambertSkymp** [comment]
Сейчас не смогу проверить и дать больше информации, у меня опять произошел баг после смерти, про который я отпишу, в данный момент я нечего во всех смыслах не могу делать, кроме как бродить по Вайтрану

**Comment by LambertSkymp** [comment]
> Не удаётся воспроизвести, просто находясь в игре. Может быть, нужно подбирать кошельки или золото из сундуков?

Сейчас не смогу проверить и дать больше информации, у меня опять произошел баг после смерти, про который я отпишу, в данный момент я нечего во всех смыслах не могу делать, кроме как бродить по Вайтрану

**Comment by LambertSkymp** [comment]
> Не удаётся воспроизвести, просто находясь в игре. Может быть, нужно подбирать кошельки или золото из сундуков?

Сделал новый аккаунт и нашел как вызвать метод, я набрал 1314 септимов с помощью сундуков торговцев, после чего вышел и у меня был 1 септим который теперь так-же растет с каждой секундой

**Comment by Pospelove** [comment]
@LambertSkymp Прошу протестировать ещё раз с **сундуками торговцев**, чтобы подтвердить баг окончательно. Также, приложить местоположение этих сундуков (скриншот, название локации и ID сундука).

**Comment by LambertSkymp** [comment]
Я думаю что баг не зависит от сундуков торговцев, а от количество подобранного золото но для этого видео я опять использовал такой сундук, во общей сложности я использовал 1000 золото из сундука торговца, и 200 золото из обычных мест, я не знаю как добыть ID именно сундука, по этому вставлю скриншот и название локации - Обожжённый молот (Код локации - RiftenBlacksmith)
![ScreenShot17](https://user-images.githubusercontent.com/74125507/98544704-0ab86a80-229d-11eb-82c0-960536d7bc98.png)


https://youtu.be/ook--FcVU9U

**Comment by LambertSkymp** [comment]
Я попробовал собрать 1000 золотых через обычные сундуки и эффект тот же, после перезахода у тебя 1 золото которое потом постепенно растет.

**Comment by Pospelove** [comment]
Не удается воспроизвести. Баг существует?
Желательно создать 2 аккаунта и протестировать следующие случаи:
1) Лут сундуков
2) Лут мешочков с золотом

У меня есть подозрение, что 2 работает неправильно.

**Comment by LambertSkymp** [comment]
> Не удается воспроизвести. Баг существует?
> Желательно создать 2 аккаунта и протестировать следующие случаи:
> 
> 1. Лут сундуков
> 2. Лут мешочков с золотом
> 
> У меня есть подозрение, что 2 работает неправильно.

Да! баг ещё существует, так-же как и баг с мешками, записал 3 Видео на которых показал что мешочки не работают, так-же показал что на новых аккаунтах после 999 золота будет происходит баг с золотом, так-же показал что на 998 этого бага не происходит.
https://youtu.be/G_WNz0SU4Ug
https://youtu.be/ORipwtoeFME
https://youtu.be/ZfahromiYiQ

**Comment by Pospelove** [comment]
Вижу. Прошу тестеров узнать все детали и подготовить свой отчет, когда ситуация с лутом наладится.

**Comment by Daler-Karimov** [comment]
@Pospelove Установлено, что золото не подбирается с мешочков (https://youtu.be/CA_UTdvU76s), но подбирается с контейнеров типа: "сундук" (https://youtu.be/Ddo-2H4xBD0). Проблема с "капающим золотом" является частным случаем #73  issues. Данное #10 issues прошу закрыть. 

Проблема с неподбираемым лутом является отдельной темой тестов.
