### ISSUE TITLE
Грот Сломанное Весло - невозможно выйти из локации.

### ISSUE THREAD

**Issue by Daler-Karimov** [skyrim-multiplayer/issue-tracker#11]
## Описание

При входе в данную локацию невозможен выход, так как не срабатывает перемещение игрока в локацию: "Скайрим" на месте триггера расщелины пещеры. Ловушка, необходимо создавать новые аккаунты.

## Воспроизведение

Зайти в пещеру.

## Локация, FormID

BrokenOarGrotto01 (Грот Сломанное Весло), 000BA599.

## Вероятность воспроизведения

100%, было совершенно более 10-ти тестов с разных аккаунтов. 

## Ожидаемый результат

Должен состояться выход из локации т.е. телепортация из нее в локацию:"Скайрим"

## Среда исполнения

Windows 10х64
Steam-версия Skyrim SE и пиратская копия игры.

## Видео/скриншоты

https://youtu.be/7Curc_dPegU

**Comment by Banan1447** [comment]
https://www.youtube.com/watch?v=zxGATXN-iRA&ab_channel=banan47
Проверили нужен человек(специфичный) для того что бы вытащить из локи

**Comment by Daler-Karimov** [comment]
https://www.youtube.com/watch?v=zxGATXN-iRA&feature=youtu.be&ab_channel=banan47

Данная локация вызывает десинхронизацию: сбивает интерфейс чата, не отображает сообщения, создает локальный мир. Выйти из локального мира, как всегда помог перезаход в игру. Игрок, который застрял (женщина с каштановыми волосами), а точнее его персонаж - оставался в локации на момент обновления сервера.

0:40/2:09 - игрок смог выйти из пещеры, только когда зашел другой игрок

**Comment by Daler-Karimov** [comment]
@Pospelove баг исправлен.
