### ISSUE TITLE
Более подробное описание зависания у бурана на Глотке Мира

### ISSUE THREAD

**Issue by Daler-Karimov** [skyrim-multiplayer/issue-tracker#12]
## Описание

При входе в буран происходит высокая нагрузка на игру. Есть предположение, что за это ответственен триггер нанесения урона.

## Воспроизведение

Войти в буран

## Локация, FormID

HighHrothgar (Высокий Хротгар),00087764.

## Вероятность воспроизведения

Было проведено около 10-ти тестов. Вероятность 100%

## Ожидаемый результат

Должен пройти урон по игроку и убить (дальше находится триггер ответственный за kill)

## Среда исполнения

Windows 10х64
Steam-версия Skyrim SE и пиратская копия игры.

## Видео/скриншоты

Если баг воспроизводится не всегда, либо для этого требуется более 1-2 игроков, приложите видео.
https://youtu.be/csdr_ht6vls - процесс зависания игры
https://youtu.be/wxpbQQC45G8 - процесс зависания загрузки

**Comment by Pospelove** [comment]
Дублирует #7. В дальнейшем информацию нужно вносить в существующий репорт.
