### ISSUE TITLE
Появление около ворот Вайтрана вызывает диалог со стражником, что приводит к вылету/багу

### ISSUE THREAD

**Issue by Daler-Karimov** [skyrim-multiplayer/issue-tracker#13]
## Описание

Если при загрузке локаций, соответственно при переходе между ними и/или входе в игру с игроком будет совершенно взаимодействие НПС, то происходит тихий вылет. Проблема в том, что при этой самой загрузке локаций, на мгновенье появляются НПС и сразу пропадают. Есть предположение, что это вызвано задержкой между сервером и игроком или незаконченной загрузкой или низкой скоростью интернета или слабым конфигом компьютера, которому нужно больше времени на загрузку. 

## Воспроизведение

Перейти, загрузиться в локацию, где бы рядом стоял НПС. Пример: Ворота Вайтрана где стражник начинает диалог о входе в город. Намного чаще наблюдается после смерти игрока, который выходит из города.

## Локация, FormID

Любое место.

## Вероятность воспроизведения

50% - обычно. 100% после смерти.

## Ожидаемый результат

Не должны появляться НПС.

## Среда исполнения

Windows 10х64
Steam-версия Skyrim SE и пиратская копия игры.

## Видео/скриншоты

https://youtu.be/n1QI_Kvbxbo

**Comment by Daler-Karimov** [comment]
Исправлены вылеты, но НПС появляются, при входе и выходе из локаций, если по умолчанию в непосредственной близости от игрока, который перешел локации, стоит спавн НПС. Баг модифицировался, теперь НПС не пропадают со временем полной загрузки локации. 


Чтобы воспсроизвести, нужно перейти из локации в локацию, где рядом с дверью или элементом перехода, находится спавн НПС. Пример: двери Вайтрана, где при переходе в обе стороны рядом стоят спавны стражников или Солитьюд, как на скриншотах ниже.

Видео: https://youtu.be/ViUdRh57Hi8

![The_Elder_Scrolls_V_Skyrim_Special_Edition_Screenshot_2020 11 09_-_22 17 11 05](https://user-images.githubusercontent.com/61763100/98700011-c86c5780-2388-11eb-906a-73a2fa066c01.png)
![The_Elder_Scrolls_V_Skyrim_Special_Edition_Screenshot_2020 11 09_-_20 47 38 47](https://user-images.githubusercontent.com/61763100/98700022-caceb180-2388-11eb-8c59-12bf6e9f3b1f.png)

**Comment by Pospelove** [comment]
Баг всё ещё существует?

**Comment by Daler-Karimov** [comment]
Баг все еще частично существует. При прогрузке локаций НПС все равно появляются, но на момент, как только локация полностью прогружается, они пропадают. Вылеты не вызывают больше.

-

**Comment by Pospelove** [comment]
Это ожидаемое поведение. Закрываю.
