### ISSUE TITLE
Круг ада Вайтрана/Ловушка Вайтрана

### ISSUE THREAD

**Issue by LambertSkymp** [skyrim-multiplayer/issue-tracker#19]
## Описание

После смерти где-либо я ресаюсь в Вайтране, но я ресаюсь в состояние "Отключенном" Я не могу подбирать вещи, а если подберу они сразу пропадут, а у замков и дверей появляется функция взлома. При попытке выйти из Вайтрана на секунду меня встречает черный экран и стражник который говорит - Стой! - После чего игра крашится, во время перезахода я появляюсь в воздухе где-то под текстурами и падаю к своей смерти, и в который раз ресаюсь в храме Кинарет в "Отключенном" состояние, если не выходить из Вайтрана а попробовать выйти и в храме то после перезахода я окажусь так-же под текстурами, и после чего умру при падение, всё что я могу делать это свободно ходить по Вайтрану за исключением выхода. 

P.S До 08.11.2020 Обновление, спастись из этого бага я смог когда вышел из Вайтрана, и после очередного краша я решил пойти спать, и на следующий день захода увидел, что был за воротами и мне нужно было создавать персонажа заного, после этого момента я не умирал до этого дня, и этот баг опять произошел когда я туда попал.

P.S.S Ко всему прочему не имея возможности нечего делать, я могу видеть чат и что в нем пишут.

## Воспроизведение

Нужно умереть от чего либо, и оказаться Вайтране после чего попробовать выйти или подобрать предмет, или выйти в храме.

## Локация, FormID

Вайтран, Ворота из Вайтрана

## Вероятность воспроизведения

Точно могу сказать я уже умирал и выходил из Вайтрана на начальных версиях нормально, но после нескольких обнов, когда я умер этого произошло, как я понял у многих этого бага нету, но есть те у кого он тоже есть, когда я писал в чате и спрашивал у других был ещё один человек с такой же проблемой, так-же видел в дискорде bug-rep кто-то об этом писать.

## Ожидаемый результат

После смерти я могу подбирать предметы как в храме Кинарет так и во всем Вайтране. Могу выходить из Вайтрана не вызывая краш. Вход в игру после выхода в Вайтране не должен спавнить меня под текстуры и убивать при падание.

## Среда исполнения

Версия Windows 10
Steam-версия Skyrim SE

## Видео/скриншоты
Полный обзор
https://youtu.be/d72FDrp4ODI

**Comment by LambertSkymp** [comment]
ОГРОМНЫЙ ПРОГРЕСС! Мне удалось найти способ убрать этот баг и узнать задатки почему он может происходить!
Отчаявшись я решил, снова использовать команды, используя coc SolitudeOrigins я оказался в нем, но в "Отключенном" состояние, по этому решил перезайти думая что-то будет иначе чем в Вайтране, к моему удивлению я опять оказался под текстурами, но на этот я стоял на полу а не падал к нему, после нескольких таких же тестов в других местах, я пришел обратно в это место так-как оно из немногих которых ставило тебя на землю чем ставило в воздухе после чего ты умирал, опять вздохнув и бегая по просторам плоской земли, поставил персонажа на авто-бег и ушел в туалет, после того как я вернулся, увидел что мой персонаж уперся в огромную гору, посреди этой плоской земли, после осмотра и команды tcl, я определил что это место "Ведьмино гнездо" после чего я вспомнил как я умер чтобы попасть в Вайтран, и сделать этот баг, я был в "Ведьмино гнездо" и потом чтобы быстро выбраться от туда использовал coc SolitudeOrigin, я там я прошел в другое место, после игра крашнулась, и через перезаход, я был над текстурами и упал вниз к своей смерти, и тогда случился баг с Вайтраном. К моему удивлению я нашел в "Ведьмино гнездо" ещё одного игрока который жаловался на удаление персонажей и по этому использовал команды, и как-то получил баг с Вайтраном, после чего он пошел лутатся в "Ведьмино гнездо" Не-знаю вызывается ли этот баг только если делать то что я перечислил, я уже не помню свое первую встречу с багом, но после того как я выбрался из "Ведьмино гнездо" без команд и вышел в Скайрим я был уже не в "Отключенном" стояние могу подбирать вещи, и после того как пошел в Солитюд где при выходе я падал вниз, через перезаход всё было в порядке и я заспавнился не под текстурами.

**Comment by Pospelove** [comment]
Дублирует #16
