### ISSUE TITLE
Падение сервера после взаимодействия с топором

### ISSUE THREAD

**Issue by Daler-Karimov** [skyrim-multiplayer/issue-tracker#2]
## Описание

После взятия топора, происходит отключение сервера, игроки выпадают из синхронизации в локальную игру.

## Воспроизведение

Для воспроизведения, топор необходимо подобрать в инвентарь.

## Локация, FormID

Liar's Retreat (Пристанище лжеца), 000AA20C.

## Вероятность воспроизведения

100% 

## Ожидаемый результат

Ожидается подбор предмета в инвентарь, в данном случае фалмерского топора.

## Среда исполнения

Windows 10 x64
Skyrim SE - лицензия и пиратская копия.

**Comment by Pospelove** [comment]
За это время сервер не упал ни разу. Исправлено.

**Comment by Daler-Karimov** [comment]
Между тестами несколько часов.
![The_Elder_Scrolls_V_Skyrim_Special_Edition_Screenshot_2020 11 11_-_20 14 34 72](https://user-images.githubusercontent.com/61763100/98852547-df827680-2468-11eb-80a0-0f0eee5fcfa5.png)
![Uploading ScreenShot110.png…]()

**Comment by Daler-Karimov** [comment]
Между тестами несколько часов. Баг исправлен.
![The_Elder_Scrolls_V_Skyrim_Special_Edition_Screenshot_2020 11 11_-_20 14 34 72](https://user-images.githubusercontent.com/61763100/98852614-f7f29100-2468-11eb-9bce-1bc76ab7feef.png)
![ScreenShot110](https://user-images.githubusercontent.com/61763100/98852620-fa54eb00-2468-11eb-9101-897b96b3b4ea.png)
