### ISSUE TITLE
Не полное сохранение данных о персонаже.

### ISSUE THREAD

**Issue by witheredwojak** [skyrim-multiplayer/issue-tracker#23]
## Описание

Первое, что не сохраняется и сбрасывается после перезахода, это открытые места на карте. Второе, это экипированное оружие, после перезахода нужно надевать его заново. Насчёт прокачки писать не стану, ибо понятно, что пока она специально не сохраняется.

## Воспроизведение

Открыть некоторые места на карте, экипировать оружие и перезайти.

## Вероятность воспроизведения

Всегда.

## Ожидаемый результат

Сохранение описанных выше данных.

## Среда исполнения

Win10 x64.
Пиратка.

**Comment by Pospelove** [comment]
> Первое, что не сохраняется и сбрасывается после перезахода, это открытые места на карте. 

Это не баг, просто синхронизация маркеров отсутствует. Я бы также дополнил, что назначенные в избранном горячие клавиши не сохраняются.

> экипированное оружие, после перезахода нужно надевать его заново

Это правда, но мы пока не можем исправить это(
Я поставил метку "Не будет исправлено". Возможно, в будущем вернемся к этому.
