### ISSUE TITLE
Жизнь по ту сторону мира 

### ISSUE THREAD

**Issue by BorodachDelete** [skyrim-multiplayer/issue-tracker#25]
## Описание

При смерти персонаж из локации где тот умер переносит в святилище ,там он попадет в одиночную игру (относительно) , не может открывать двери и с чем либо взаимодействовать ! После перезахода он спавнится в воде под картой , но на самом деле он остается на месте смерти просто его тело отбрасывает в зону храма где та не прогрузилась ! Такая проблема была уже у троих. 

Двоя из них решили её путем прилета в ту локацию где умерли в виде без текстурных гор указанных на скриншотах ниже в данном случае это Маркарт.

 На 1 скриншоте пока неизвестно , игрок не отписал результат помощи 

## Воспроизведение

После смерти не в открытом мире персонажа перебрасывает в Вайтан , где тот при невозможности открыть дверь перезаходит , после чего оказывается в воде за текстурами 

## Локация, FormID

Любая закрытая локация , в данном случае Маркарт , после телепортации Святилище в Вайтране 

## Вероятность воспроизведения

15%

## Ожидаемый результат

Я умираю и восстанавливаюсь в нормальном игровом режими , а не отброшенный на несколько кубов текстур в воде!

## Среда исполнения

Версия Windows 10
Steam-версия Skyrim SE

## Видео/скриншоты
скриншот другого игрока , был ещё один , но он удалил свой скрин из баг-репорт 

![ScreenShot34](https://user-images.githubusercontent.com/74230074/98637717-9e944000-234a-11eb-93d5-79189965777c.png)

![20201109205441_1](https://user-images.githubusercontent.com/74230074/98637592-64c33980-234a-11eb-9c9f-5da34536cbd3.jpg)

![20201109205437_1](https://user-images.githubusercontent.com/74230074/98637618-6b51b100-234a-11eb-8386-1bfcf0e9499d.jpg)

**Comment by Pospelove** [comment]
Спасибо. Будет исправлено. Issue закрываю, т.к. дублирует #16
