### ISSUE TITLE
Отписи игроков видны в других интерьерах 

### ISSUE THREAD

**Issue by Ansgar-skymp** [skyrim-multiplayer/issue-tracker#27]
## Описание:
Игроки в интерьерах могут видеть сообщения в чате которые были отосланы из других интерьеров. 

## Воспроизведение

Поместите одного игрока в интерьер и пошлите сообщение из любого другого интерьера. 

## Локация, FormID

Общее для многих интерьеров в игре. 

## Вероятность воспроизведения

70%-90%

## Ожидаемый результат

Сообщения из чата будут видны лишь в пределах интерьера в котором находится пишущий игрок. 

## Среда исполнения

Версия Windows.
Steam-версия Skyrim SE 

## Видео/скриншоты

-

**Comment by Daler-Karimov** [comment]
@Pospelove баг исправлен. Проверено многократно.

**Comment by Daler-Karimov** [comment]
@Pospelove баг исправлен. Проверено многократно.
