### ISSUE TITLE
Рассинхрон после возрождения.

### ISSUE THREAD

**Issue by witheredwojak** [skyrim-multiplayer/issue-tracker#28]
## Описание

После смерти выкидывает из синхронизации. Чат прекрасно работает, но меня игроки не видят, как и я их. Один раз выкинуло - даже не подозревал ничего, мог взаимодействовать с контейнерами (хотя лут в них был из стандартной игры, типа помидор в бочке), перемещаться между локациями. Второй раз после смерти сразу понял, что выкинуло, не работали ворота в Вайтране и не открывались контейнеры. Напомню, что чат, несмотря на рассинхрон, работает.

## Воспроизведение

Попросить кого то прийти в Вайтран на определённую точку, самому умереть. После смерти прийти на эту же точку и узнать, видишь ли ты игрока и видит ли он тебя.

## Вероятность воспроизведения

Раньше такого, вроде бы, не было, сегодня все 2 раза, что умирал - в обеих выкинуло из синхры.

## Среда исполнения

Win10 x64.
Пиратка.

**Comment by Daler-Karimov** [comment]
issue-tracker этого бага, уже присутствует в списке. Прошу удалить.
