### ISSUE TITLE
Спавнюсь в LOD версии Вайтрана.

### ISSUE THREAD

**Issue by witheredwojak** [skyrim-multiplayer/issue-tracker#30]
## Описание

После захода на сервер появляюсь не в самом Вайтране, а его LOD версии. То есть, по сути, я вышел из игры в локации Вайтран, игра запомнила моё местоположение, но не локацию, благодаря чему после захода на сервер я появляюсь на том-же месте, но уже в локации обычного мира. Пока что чинится баг, если подбежать к воротам, нажать на них и игрока перекинет в нормальную версию города. При таком переходе так-же спавнится стражник, который с тобой разговаривает, если его ударить он исчезнет. Несмотря на стражника из синхронизации не выкидывает.

## Воспроизведение

Выйти из игры в Вайтране и зайти обратно в игру.

## Вероятность воспроизведения

Впервые сталкиваюсь, хотя видел этот баг у других игроков.

## Среда исполнения

Win10 x64.
Пиратка.

## Видео/скриншоты

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 11 10 - 16 59 45 58](https://user-images.githubusercontent.com/66310741/98692071-62c39f80-2377-11eb-8d43-8794c8380208.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 11 10 - 17 00 16 99](https://user-images.githubusercontent.com/66310741/98692076-63f4cc80-2377-11eb-8361-33127a3cb674.png)

**Comment by Daler-Karimov** [comment]
issue-tracker этого бага, уже присутствует в списке. Прошу удалить.
