### ISSUE TITLE
При разрыве соединения не переподключает к серверу.

### ISSUE THREAD

**Issue by Daler-Karimov** [skyrim-multiplayer/issue-tracker#34]
## Описание

Игрок не переподключается к серверу при обрыве соединения. Причина судя по всему в том, что сервер отправляет игроку пакеты данных (входящий трафик) и в случае если сервер не получает отклика от клиента игрока (исходящий трафик, но клиент его и не отправит если не получит входящий), то он не возвращает его на сервер. При обрыве соединения прекращается обмен пакетами и игрок не переподключается - попадая в локальный мир.

## Воспроизведение

Произвести обрыв соединения. 

## Локация, FormID

Вне зависимости

## Вероятность воспроизведения

?

## Ожидаемый результат

При разрыве и повторном пересоединении клиента игрока, сервер должен его переподключить.

## Среда исполнения

Windows 10х64
Steam-версия Skyrim SE и пиратская копия игры.

## Видео/скриншоты

На видео вручную регулировались потоки исходящего и входящего трафика:
https://www.youtube.com/watch?v=0g5wY8-Gr08&feature=youtu.be

**Comment by Pospelove** [comment]
Заметил данную проблему на стриме Xccane. Баг всё ещё существует, хотя воспроизведение затруднено.

**Comment by Daler-Karimov** [comment]
@Pospelove баг стоит на очереди в тестировании. В течении 1-3 дней будет ответ.

**Comment by Banan1447** [comment]
https://clck.ru/S7sny Битый час издеваюсь над подключением , реконнект стабильно

**Comment by Daler-Karimov** [comment]
@Pospelove баг исправлен, тесты показывают что переподключение работает корректно. Отчет: https://clck.ru/S7sny

**Comment by Pospelove** [comment]
Хорошо. Закрываю. Упомяните меня в данной issue, если баг появится.
