### ISSUE TITLE
Неправильный график онлайна после перезапуска сервера

### ISSUE THREAD

**Issue by ralencode** [skyrim-multiplayer/issue-tracker#38]
## Описание

В 13:14 11.11.2020, 09:09 11.12.2020, 11:18 11.12.2020 по Гринвичу у всех игроков разом пропадал доступ к серверу примерно на 1 час, а сейчас, после последнего отключения, счётчики (на сайте skymp.io и в лаунчере) некорректную информацию об онлайне (0, но люди на сервере есть, только что проверил).

## Воспроизведение

Посмотреть график на https://skymp.io/

## Вероятность воспроизведения

100%

## Ожидаемый результат

Корректная работа счётчиков и исправление причины массовых отключений

## Среда исполнения

Любая

## Видео/скриншоты

Не требуются.

**Comment by Pospelove** [comment]
https://media.discordapp.net/attachments/689965187389980737/776400089861062666/unknown.png

**Comment by Daler-Karimov** [comment]
Более баг не наблюдается.
