### ISSUE TITLE
Логово Моварта

### ISSUE THREAD

**Issue by Ansgar-skymp** [skyrim-multiplayer/issue-tracker#39]
## Описание

Управление перестает отвечать при попытке войти в локацию "Логово Моварта". В итоге переход на локацию так и не случается. 
## Воспроизведение

Пройти к локации "Логово Моварта" и войти вн нее.

## Локация, FormID

Баг связан с локацией Логово Моварта 

## Вероятность воспроизведения

100%

## Ожидаемый результат

Осуществляется переход в локацию без всяких проблем.

## Среда исполнения

Версия Windows.
Steam-версия Skyrim SE.

## Видео/скриншоты

-

**Comment by Pospelove** [comment]
Нельзя было войти, т.к. сервер падал. Считаем за дубликат #40
