### ISSUE TITLE
Не всегда сохраняет положение по высоте

### ISSUE THREAD

**Issue by VitaliyMubarakov** [skyrim-multiplayer/issue-tracker#4]
## Описание

После загрузки есть маленький шанс заспавниться в небе

## Воспроизведение

Перезаходить. 

!! Я не знаю есть ли тут связь, но подлетел я на стоянке великанов, а в ваниле это самый лёгкий путь для полёта

## Локация, FormID

Стоянка великанов

## Вероятность воспроизведения

~5% (на угад)

## Ожидаемый результат

заспавниться там где вышел

## Среда исполнения

Версия Windows. - Windows 10 Pro, 19042.572
Steam

## Видео/скриншоты

![20201108131838_1](https://user-images.githubusercontent.com/58411554/98458209-25b9aa80-21c9-11eb-95fd-fe1e755687f7.jpg)

**Comment by VitaliyMubarakov** [comment]
Discord: i3sN#8151

**Comment by Pospelove** [comment]
Я думаю, что это не вероятностная проблема, а проблема, имеющая конкретную причину и, соответственно, конкретный способ воспроизведения. Пожалуйста, изучите проблему подробнее и дополните issue.

**Comment by Daler-Karimov** [comment]
@Pospelove баг найден.

##Воспроизведение 

Есть два сценария:
1) Локация "Город": Необходимо зайти в любое здание внутри города, выйти из игры, зайти в игру и сразу попытаться выйти. Произойдет анимация двери, ее открытие, но персонаж не попадет в локацию города и не сможет выйти из здания. При перезаходе в игру, игрока кидает в нулевые координаты, будучи в локации города. Соответственно это стоянка великанов, но мыльная, поскольку игрок фактически находится в локации города, но появляется за его пределами.

Видео: https://youtu.be/_AnF_UXzM2Y

2) Локация "Скайрим": Необходимо зайти в любое здание внутри скайрима, например в конюшню, выйти из игры, зайти в игру и сразу попытаться выйти. Произойдет анимация двери, ее открытие, но персонаж не попадет в скайрим и не сможет выйти из здания. При перезаходе в игру, игрока кидает в нулевые координаты, но в отличии от первого сценария в нормальный скайрим.

Видео: https://youtu.be/VtcxdHrX4V8 / https://youtu.be/yeJFre78ouc / https://youtu.be/v5jPoi1KXqc - с пояснениями / https://youtu.be/cfgpYQIybQo - полный цикл воспроизведения / https://youtu.be/73WjkaMg-ZQ - полный цикл воспроизведения ( 0:11 - выход из игры, 0:12 - заход в игру, 0:18 - попытка выйти из локации, 0:26 - выход из игры, 0:27 - заход в игру, 0:32 - падение)


##Предположение

ЕСЛИ после следующих действий: 1) Зайти в здание 2) Выйти и игры 3) Зайти в игру - попробовать подождать минуту и дать локации прогрузиться (кстати на это время сбивается освещение), а не стараться выйти сразу, то при активации двери игрок спокойно выйдет из здания, без последствий. Мы предполагаем, что игрок, после быстрой активации двери спустя пары секунд от захода в игру, регистрируется сервером как вышедший из здания и находящийся в городе с соответсвующими координатами, но сохраняется по координатам внутри здания (возможно любой интерьер - это нулевые координаты). По итогу, поскольку игрок не может появится по координатам внутри здания, на локации скайрима и/или города (там координаты распространяются и на город и на провинцию) его кидает в нулевые координаты на стоянке великана. Мыло - если первый сценарий, ибо это внешний скайрим на локации города. Прогруженный скайрим - игрока кинуло в нулевые координаты как раз в локации скайрима, поскольку именно в этой локации игрок обрабатывался.

А еще в нулевых координатах висят в воздухе корни (серверная мусорка я полагаю?) - влияет на фпс.

**Comment by Daler-Karimov** [comment]
Дополнение к первому сценарию: В пример был взят Вайтран, для него единственного есть модель скайрима вокруг города, которую можно наблюдать, для других городов такое не реализовано. Поэтому внешний скайрим не прогружается для любых городова, кроме вайтрана и если повторить первый сценарий например в маркарте, то игрока кинет в нулевые координаты, но внешний скайрим не прогрузит, поскольку для маркарта он не прорисовывается и по факту это все та же локация: "Маркарт", но в других координатах. По итогу игрока кидает в океан, если прибежать в маркарт, то игрок действительно окажется внутри города.

Видео: https://youtu.be/xyvzPZ-ZXTk

**Comment by Daler-Karimov** [comment]
@Pospelove Баг исправлен.
