### ISSUE TITLE
Выход из игры около разрушенного дома в дальнейшем вызывает вылет 

### ISSUE THREAD

**Issue by Daler-Karimov** [skyrim-multiplayer/issue-tracker#46]
## Описание

Если выйти из игры, после нахождения в доме (не внутренняя локация, находится в скайриме), и потом зайти, то будет вылет. Чтобы не допустить краша, нужно быстро убежать от этого места.

## Воспроизведение

Прийти в дом и перезайти в игру

## Локация, FormID

"Скайрим", внешняя без ID (в скринах есть координаты)

## Вероятность воспроизведения

100%

## Ожидаемый результат

После перезахода не должно быть вылета.

## Среда исполнения

Windows 10х64
Steam-версия Skyrim SE и пиратская копия игры.

## Видео/скриншоты

![ScreenShot77](https://user-images.githubusercontent.com/61763100/99531747-409fd200-29b4-11eb-92d5-a923daa1a335.png)
![ScreenShot76](https://user-images.githubusercontent.com/61763100/99531751-43022c00-29b4-11eb-8785-f3de5ae9c108.png)
![ScreenShot75](https://user-images.githubusercontent.com/61763100/99531753-44335900-29b4-11eb-8e2b-ef01c71d3296.png)

**Comment by Pospelove** [comment]
> Steam-версия Skyrim SE и пиратская копия игры.
 
что бы это значило?

> 100%

не воспроизводится с 2 раз. баг всё ещё существует? или может у меня лицензия просто?

**Comment by Daler-Karimov** [comment]
@Pospelove раньше абсолютно у всех воспроизводилось, вероятно это был частный случай другого бага, который прошел фикс. Баг отправлен на повторное тестирование.

А строка: "Steam-версия Skyrim SE и пиратская копия игры", значит что это было проверено и воспроизведено как на лицензии, так и на пиратке.

**Comment by Daler-Karimov** [comment]
@Pospelove установлено, что баг пропал. Многочисленные тесты не выявили сбоев, вероятно баг был исправлен в комплексном фиксе другого.

https://youtu.be/qy87tRlkwbE
