### ISSUE TITLE
Волшебная западня  

### ISSUE THREAD

**Issue by BorodachDelete** [skyrim-multiplayer/issue-tracker#47]
## Описание

Я нажимаю на предмет, и он не подбирается , в том числе дверь тоже не открывается  ! цитата игрока: Застряла в локации Мидден. При попытке выйти дверь не активируется (пробовала все три выхода) и пропадает возможность взаимодействовать с чем-либо в локации. Перезапуск игры, лаунчера и компьютера не помог.

PS Мидден тьма , тот же процесс , попал я туда ударом о тележку попал под воду после чего благополучно скончался , но при перезаходе попал в  Мидден тьма 

pss ТАМ ЕСТЬ ВЫХОД И вот как до них догадался Dubstep, а Nekto (применила)  ! 

Там закономерность: ты за  секунды после начала синхронен должен добраться до выхода (не важно как) , но после (примерно 7 сек) ты уже не в этом мире , я же за долю секунды зашел в Мидден тьма и остался там , где выбраться можно за 10-12 секунду но не в скайрим а обратно в обычный Миддан , где через тсл после перзахода надо быстрее попасть к выходу , а не то ты снова останешься там

Дело в том что там отключается сам выход и подбор предметов 
Это подтверждает то что в темном Миддене я не мог выйти через пещеру
Я просто зависал в воздухе

## Воспроизведение

При попадание в локацию 

## Локация, FormID
Мидан , Коллегия Винтерхолда 

## Вероятность воспроизведения

90%
## Ожидаемый результат

Выбраться из подземелья 

## Среда исполнения

Версия Windows 10
Steam-версия Skyrim SE 

## Видео/скриншоты

Если баг воспроизводится не всегда, либо для этого требуется более 1-2 игроков, приложите видео.

![20201118182215_1](https://user-images.githubusercontent.com/74230074/99538005-2f63bf00-29ce-11eb-98c6-5407646dbb49.jpg)
![20201118195449_1](https://user-images.githubusercontent.com/74230074/99549331-58d71780-29db-11eb-8848-8f8f239cc93d.jpg)
![DP55wSO1](https://user-images.githubusercontent.com/74230074/99556487-62fd1400-29e3-11eb-8b57-4eb6073cdb96.jpg)

**Comment by dimati944** [comment]
Тоже ловил этот баг. Из него помог выбраться "coc" (консольная команда если что)

**Comment by dimati944** [comment]
![image](https://user-images.githubusercontent.com/74133241/99586100-d02b9c00-2a19-11eb-81cb-d6a1d0ca7c3a.png)
такая тема уже есть

**Comment by Pospelove** [comment]
Дублирует #35
