### ISSUE TITLE
РП чат работает не правильно

### ISSUE THREAD

**Issue by dimati944** [skyrim-multiplayer/issue-tracker#48]
## Описание

РП чат который должен работать только в 1 локации работает на всех схожих. Например из таверны винтерхолда "слышны" разговоры игроков в таверне Виндхельма или Данстара. В тронном зале того же Винтерхолда, читаются диалоги из тронных залов других городов. Связь работает в обе стороны и видят это все игроки этих локаций, что очень мешает только зарождающемуся РП процессу. В ближайшее время могу дополнить этот пост видео или скринами если это необходимо, хотя я думаю что достаточно описал проблему.

## Воспроизведение

Написать фразу в 1 тронном зале, ее увидят в другом

## Локация, FormID

Замечал это в тавернах и тронных залах. В дальнейшем дополню этот пост новой информацией.

## Вероятность воспроизведения

100%

## Ожидаемый результат

Чат будет работать только в местной локации, что логично.

## Среда исполнения

Версия Windows.
Steam-версия Skyrim SE

## Видео/скриншоты

Чуть позже дополню.

**Comment by Pospelove** [comment]
Дублирует #27. Будет исправлено.
