### ISSUE TITLE
При входе грузится LOD версия Вайтрана

### ISSUE THREAD

**Issue by VitaliyMubarakov** [skyrim-multiplayer/issue-tracker#5]
## Описание

При входе в Вайтране не прогружаются текстуры, а дверь вайтрана ведёт не из Вайтрана, а в Вайтран.

## Воспроизведение

Есть шанс при перезаходе.

## Локация, FormID

Вайтран (возможно любой город, но Вайтран стандартный)

## Вероятность воспроизведения

10% (на угад)

## Ожидаемый результат

Нормальный город

## Среда исполнения

Версия Windows. - Windows 10 Pro, 19042.572
Steam

## Видео/скриншоты

![20201106162230_1](https://user-images.githubusercontent.com/58411554/98458271-d627ae80-21c9-11eb-9b35-f1df14fd4af5.jpg)

**Comment by VitaliyMubarakov** [comment]
Discord: i3sN#8151

**Comment by Pospelove** [comment]
Я думаю, что это не вероятностная проблема, а проблема, имеющая конкретную причину и, соответственно, конкретный способ воспроизведения. Пожалуйста, изучите проблему подробнее и дополните issue.

**Comment by Daler-Karimov** [comment]
Хочу обратить внимание, что это не локация: "Вайтран", а локация: "Скайрим" на тех же координатах.

**Comment by meecosha** [comment]
https://youtu.be/aF3_dHk12Zs

Видео с этим багом. Он появляется сразу после загрузки

**Comment by Pospelove** [comment]
Мне не удаётся воспроизвести. Есть ли действия, которые влияют на это?

**Comment by meecosha** [comment]
> Мне не удаётся воспроизвести. Есть ли действия, которые влияют на это?

У меня это происходило почти каждый раз, когда вайпался персонаж. В данном случае я тоже создавал персонажа с нуля, и этот баг произошёл опять. Не знаю, как воспроизвести по-другому

**Comment by Pospelove** [comment]
Предположим, что баг исправился вместе с вайпом. Закрываю пока. Если баг ещё раз повторится при перезаходе, не из-за смерти, нажмите **Reopen**, чтобы снова открыть issue.
