### ISSUE TITLE
Глотка Мира - Стена Ветра

### ISSUE THREAD

**Issue by LambertSkymp** [skyrim-multiplayer/issue-tracker#51]
## Описание

Чуть ниже -Глотка Мира- есть стена ветра которая не должна тебя пускать дальше верх по горе, при приближение и выхождение в этот ветер игра крашится, после чего если персонаж не умер за каждым следующим входом будет идти краш, что погубило уже 2 моих персонажей так-как они не могут выйти из этого места.

## Воспроизведение

Войти в ветер, находится в ветре

## Локация, FormID

ThroatOfTheWorld01

## Вероятность воспроизведения

100%

## Ожидаемый результат

Барьера быть не должно/Барьер не должен вызывать краш

## Среда исполнения

Windows 10
Steam-версия Skyrim SE

## Видео/скриншоты

![7428497-1461292782](https://user-images.githubusercontent.com/74125507/99867984-1c680f00-2bc7-11eb-9493-0e5720c89823.jpg)

**Comment by dimati944** [comment]
#7 уже известно
