### ISSUE TITLE
Крашит во время загрузки в меню

### ISSUE THREAD

**Issue by Battleparrot** [skyrim-multiplayer/issue-tracker#53]
## Описание

Игра стала вылетать на стадии загрузки в меню. Заметил что вылет происходит на стадии логгирования персонажа (см. скриншот)

## Воспроизведение

Возник баг во время рестарта _сервера_, я в это время перешёл из одной локации в другую
 UPD. Кое-что хочу добавить, я вышел из игры в момент когда рядом со мной стояло кучу народу.

## Локация, FormID

Крепость в Маркарте

## Вероятность воспроизведения

Шанс повторить специально данный баг очень мал, но он есть

## Ожидаемый результат

Пустите меня пожалуйста поиграть  на сервер :c

## Среда исполнения

Windows 10
Йохохо-версия Skyrim SE.

## Видео/скриншоты

![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 11 22 - 16 55 54 89](https://user-images.githubusercontent.com/72072409/99901862-ea989a80-2ce3-11eb-8d76-d622b4290eb2.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 11 24 - 21 03 56 58](https://user-images.githubusercontent.com/72072409/100112604-9e8f5680-2e99-11eb-890f-1ee370e4810d.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2020 11 24 - 21 04 24 52](https://user-images.githubusercontent.com/72072409/100112619-a2bb7400-2e99-11eb-87fd-77bdf6df6fa4.png)

**Comment by Daler-Karimov** [comment]
@LunarWyvern Что вы подразумеваете под рестартом? Возрождение, перезаход, рестарт сервера, заход в игру после вылета?

**Comment by Battleparrot** [comment]
> @LunarWyvern Что вы подразумеваете под рестартом? Возрождение, перезаход, рестарт сервера, заход в игру после вылета?

Да, не пояснил. Всё произошло после рестарта сервера

**Comment by Pospelove** [comment]
@LunarWyvern Приветствую. Постараемся всё проверить и исправить данную проблему. Прошу по возможности приложить скриншот точного места в игре, в котором произошла проблема (можно сделать в одиночной игре).
@Daler-Karimov Прошу начать проверку

**Comment by Battleparrot** [comment]
@Pospelove Приветствую. Вернусь с работы, сделаю скриншоты. Заметил что это очень распространённая проблема у игроков(в дискорде много жалоб на вылеты в меню). Я думаю персонаж не может загрузиться в определённой локации. Как временное решение можно сделать функцию респавна персонажа на изначальную локацию (Вайтран).

**Comment by Daler-Karimov** [comment]
@Pospelove о баге известно уже неделю, баг стоял на очереди в тестировании, пока известен не весь алгоритм воспроизведения, но уже ясно, что это связано с некоторыми локациями появление в которых вызывает это и/или некорректное сохранение данных о персонаже, что может быть вызвано некоторыми действиями, во время рассинхрона. Точный ответ будет в скором времени, возможно это связано исключительно с локацией из описания.

**Comment by Daler-Karimov** [comment]
@Pospelove  У игрока произошел сбой при сохранении персонажа на сервере. Во время перехода между локациям игроку присвоилась локация города, но с координатами помещения, т.е. воспроизведен #4 баг. Таким образом игрок получил постоянный расинхрон и именно из-за него игрок при попадании на сервере сразу появляется в рассинхроне как в баге #58

**Comment by Pospelove** [comment]
@Daler-Karimov

Это можно воспроизвести на последней версии?
Если да, является ли это отдельным багом или одним багом с #58?

**Comment by Battleparrot** [comment]
Внезапный вайп не затронул мой аккаунт как я понимаю. Игра по прежнему вылетает.
Если нужно отдам аккаунт и пароль для тестеров

**Comment by Daler-Karimov** [comment]
@Pospelove такое можно воспроизвести только при рестарте сервера, потому что этот баг является разновидностью бага #4, который  невозможно воспроизвести в силу исправленности. С #58 это не связанно, у других игроков данное место не вызывает вылетов при перезаходе в игру и/или при нахождении. Персонаж некорректно был сохранен и появляется в рассинхроне, появление в котором всегда и везде вызывает вылет и/или зависание игры.

**Comment by Pospelove** [comment]
Невозможно воспроизвести. Закрываю. Если баг произойдёт в будущем, переоткройте. Сделаю полный вайп, раз уж по факту все слетело, и персонаж починится.

**Comment by Pospelove** [comment]
Баг воспроизводится в момент падения сервера.

**Comment by Daler-Karimov** [comment]
#73 issues

**Comment by Daler-Karimov** [comment]
-> #84 issues

**Comment by Pospelove** [comment]
Закрываю в пользу #84
