### ISSUE TITLE
Забранный лут , рассинхрон 

### ISSUE THREAD

**Issue by BorodachDelete** [skyrim-multiplayer/issue-tracker#57]
## Описание

В локациях появляется лут который уже подобран , но графически отображается (поднять его нельзя) в локации которую уже за лутали  
## Воспроизведение

При входе в локацию 

## Локация, FormID

RiftenMistveilKeep

## Вероятность воспроизведения

50% после перезахода все становится как и должно быть 

## Ожидаемый результат
Синхронизация забранных предметов 

## Среда исполнения

Версия Windows10
Steam-версия Skyrim SE

## Видео/скриншоты

https://www.youtube.com/watch?v=4GKRBYccMzI&feature=youtu.be

**Comment by Daler-Karimov** [comment]
@Pospelove В ходе проведения соответствующих тестов, не было выявлено данной проблемы. При ее повторном возникновении осведомлю и попрошу открыть данное issues заново.

https://youtu.be/-6PyXJQI1Dw
https://youtu.be/XFDL6Br9kiw
https://youtu.be/8Ux-oXvO_Uw
