### ISSUE TITLE
Teleporting/Почта/Персонажи

### ISSUE THREAD

**Issue by LambertSkymp** [skyrim-multiplayer/issue-tracker#61]
## Описание

Когда я бежал через горы из Рифта в Фолкрид игра стала жутко лагать, и в консоли спамило - Teleporting..... - каждую секунду, после перезахода нечего не изменилось, только экран стал черный и я нечего не вижу.

## Воспроизведение

Пробежать через горды из Рифта в Фолкрид?

## Локация, FormID

Не уверен

## Вероятность воспроизведения

Я не уверен как это происходит у меня уже рекордное количество смертей персонажей подобными образами и совсем кончились почты для создание новых персонажей.... когда я соберусь с силами создам ещё почт чтобы проверить и отпишу прогресс.

P.S Если можете подумайте над удалением персонажа на аккаунте, у меня уже где-то 20 почт убитых персонажей за которых я не могу нечего сделать.

## Ожидаемый результат

Персонаж не будет сталкиваться с подобным явлением и сможет спокойно перебежать из одной локации в другую

## Среда исполнения

Версия Windows 10
Steam-версия Skyrim SE

## Видео/скриншоты

![ScreenShot26](https://user-images.githubusercontent.com/74125507/100259298-bb3a9580-2f50-11eb-9c2f-2bcd662ab070.png)

**Comment by Battleparrot** [comment]
@LambertSkymp приветствую, для почты советую использовать cайт https://10minutemail.net/?lang=ru, там буквально дают почту на 10 минут пользования без регистрации.

**Comment by LambertSkymp** [comment]
Спасибо не подумал даже польз
