### ISSUE TITLE
Создание уже экипированного персонажа 

### ISSUE THREAD

**Issue by Daler-Karimov** [skyrim-multiplayer/issue-tracker#63]
## Описание

При создании персонажа, он уже экипирован полностью в железную броню, что очень мешает созданию персонажа.

## Воспроизведение

Начать создание персонажа, в первый раз зайти в игру.

## Локация, FormID

Не имеет значения.

## Вероятность воспроизведения

100%

## Ожидаемый результат

Создание должно произойти без мешающих элементов брони.

## Среда исполнения

Windows 10х64
Steam-версия Skyrim SE и пиратская копия игры.

## Видео/скриншоты

![ScreenShot240](https://user-images.githubusercontent.com/61763100/100275294-be457e00-2f70-11eb-9f04-e7ae9c8ed0bc.png)

**Comment by Pospelove** [comment]
Вызвано появлением поддержки Outfit на сервере. Именно такой лут у игрока в Skyrim по умолчанию (можно легко убедиться, зайдя в главное меню и вызвав coc whiterun, например). Как бы там ни было, я это исправлю. Просто уберу лишние предметы в редакторе

**Comment by Pospelove** [comment]
исправил на уровне клиента 
```typescript
const ironHelment = Armor.from(Game.getFormEx(0x00012e4d));
Game.getPlayer().unequipItem(ironHelment, false, true);
```

**Comment by Daler-Karimov** [comment]
@Pospelove Баг исправлен.
