### ISSUE TITLE
Спонтанный вайп 26.11.2020

### ISSUE THREAD

**Issue by Daler-Karimov** [skyrim-multiplayer/issue-tracker#64]
## Описание

Произошло спонтанное обнуление аккаунтов игроков. Пострадало по приблизительным оценкам от 50-60% игроков.

## Воспроизведение

-

## Локация, FormID

Около 30-то разных не связанных друг с другом локаций.

## Вероятность воспроизведения

-

## Ожидаемый результат

Обнуления не должно было быть как факта.

## Среда исполнения

Не имеет значения 

## Видео/скриншоты

-

**Comment by Cazexotono** [comment]
Персонаж: Cazi.
Вайп не произошел.

Вчера выходил из игры где-то в час ночи.
Сегодня заходил после вайпа в шесть часов.

**Comment by Daler-Karimov** [comment]
@Pospelove процент числа игроков, которые подвергнулись обнулению доходит до 70-80%. Вайп продолжается.

**Comment by LambertSkymp** [comment]
Играл на аккаунте до 7:00 сегодня потом этим днем в 18:00 зашел и он вайпунлся, баг опять продолжился

**Comment by Daler-Karimov** [comment]
@Pospelove Баг исправлен, вайпы прекращены.
