### ISSUE TITLE
Сундук под полом в сгоревшем доме

### ISSUE THREAD

**Issue by Cazexotono** [skyrim-multiplayer/issue-tracker#65]
## Описание

Нельзя взаимодействовать с сундуком который находится под полом в сгоревшем доме. Скорее всего баг вызван тем что на области пола с которой должен взаимодействовать игрок висит скрипт ссылающийся на контейнер. 

## Воспроизведение

Баг: Взаимодействие с полом под которым находится сундук.
Обход бага: С включенным tcl спустится под пол и использовать сундук напрямую.

## Локация, FormID

Сгоревший дом возле локации "Западная сторожевая башня" (WhiterunWatchtowerExterior)(00009A26)

![99531751-43022c00-29b4-11eb-8785-f3de5ae9c108](https://user-images.githubusercontent.com/75029802/100288769-77638280-2f88-11eb-8a02-5cf6519c4b3b.png)

## Вероятность воспроизведения

Всегда (100%)

## Ожидаемый результат

Доступ к контейнеру.

## Среда исполнения

Windows 10 x64 
Steam-версия Skyrim SE

## Видео/скриншоты

https://www.youtube.com/watch?v=JD6A8Fc_LTc

**Comment by dimati944** [comment]
Предположу, что баг вызван #67

**Comment by Cazexotono** [comment]
Не связан с #67
