### ISSUE TITLE
Корона на все случаи жизни 

### ISSUE THREAD

**Issue by BorodachDelete** [skyrim-multiplayer/issue-tracker#77]
## Описание

Зубчатая корона при надевание её одевается на два типа брони , деревянная маска (Скорее всего любая другая тоже ) , закрытый шлем стражи рассвета , баг с текстурой появляется не на всех персонажах  

## Воспроизведение

Надеть корону , после этого маску и затем уже шлем стражи рассвета (без маски ничего не сработает  

## Локация, FormID

Одеть в любой можно 
## Вероятность воспроизведения

100% , шанс короны сквозь текстуры неизвестен

## Ожидаемый результат

Баг классный! Дает больше брони , но это дисбаланс так что... К черту его , либо короне 0 брони 
## Среда исполнения

Версия Windows 10
Steam-версия Skyrim SE 
## Видео/скриншоты

Если баг воспроизводится не всегда, либо для этого требуется более 1-2 игроков, приложите видео.
https://youtu.be/2O5psohIy_w

**Comment by BorodachDelete** [comment]
Возможно это из за того что у меня нет неофициального патча скайрима

**Comment by Pospelove** [comment]
Поведение оригинальной игры аналогично. Не является багом мультиплеера.
